name: Test Develop Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: BerryBrightWoods/Library
          key: Library-BeryyBrightWoods-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-BeryyBrightWoods-
            Library-
        # Run Tests
      - name: Test in ${{ matrix.testMode }}
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.1.0f1
          projectPath: ./BerryBrightWoods
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} Test Results
        # Upload Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ matrix.testMode }}-test-results
          path: artifacts
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: ${{ matrix.testMode }}-coverage-results
          path: artifacts
          if-no-files-found: error